-- AlterEnum
ALTER TYPE "ReportType" ADD VALUE IF NOT EXISTS 'REWARD_LIABILITY_MONTHLY';
ALTER TYPE "ReportType" ADD VALUE IF NOT EXISTS 'REWARD_LIABILITY_LIFETIME';
ALTER TYPE "ReportType" ADD VALUE IF NOT EXISTS 'REWARD_ALERTS_MONTHLY';
