#!/usr/bin/env python3
"""Regenerate apps/mobile/src/components/payment/upi-icons.generated.ts.

RN's self-hosted OTA does NOT reliably deliver require()'d binary image
assets to a native binary built before those files existed — the images
render blank. So the UPI payment icons are inlined as base64 data URIs in
the JS bundle (which OTA always ships in full).

Run from the repo root after adding/replacing an icon in public/upi/:
    python3 scripts/gen-upi-icons.py
"""
from PIL import Image
import base64, io, os

# Keys must match the UPI_APPS / MORE_APPS lists in DqrCheckout.tsx.
KEYS = [
    "phonepe", "gpay", "paytm", "bhim", "amazonpay", "cred", "mobikwik",
    "whatsapp", "navi", "sbi", "icici", "hdfc", "axis", "kotak", "pnb",
    "airtel", "jupiter", "scapia", "fampay", "jiopay", "tataneu", "upi",
]


def datauri(path, size=96):
    im = Image.open(path).convert("RGB").resize((size, size), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, format="PNG", optimize=True)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


def main():
    lines = [
        "// AUTO-GENERATED by scripts/gen-upi-icons.py — do not edit by hand.",
        "// UPI app icons inlined as base64 data URIs. RN's self-hosted OTA does",
        "// NOT deliver require()'d binary image assets to an older native binary",
        "// (they render blank), so payment icons are embedded in the JS bundle —",
        "// which OTA always ships in full.",
        "",
        "export const UPI_ICON_DATA: Record<string, string> = {",
    ]
    for k in KEYS:
        p = f"public/upi/{k}.png"
        if not os.path.exists(p):
            raise SystemExit(f"missing icon: {p}")
        lines.append(f'  {k}: "{datauri(p)}",')
    lines.append("};")

    mp = "apps/mobile/src/assets/momentum-icon.png"
    if os.path.exists(mp):
        lines.append("")
        lines.append(f'export const MOMENTUM_LOGO_DATA = "{datauri(mp)}";')

    out = "apps/mobile/src/components/payment/upi-icons.generated.ts"
    open(out, "w").write("\n".join(lines) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
